language: python
cache: pip
sudo: true
python:
  - "3.5"
  - "3.6"

env:
  - TEST_TYPE="test"

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="compliance"
    - python: 3.7
      dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack3 liblapack-dev

install:
  - pip install -U .[dev]
  - pip install git+https://gitlab.kwant-project.org/cwg/wraparound.git

script:
  - if [ "$TEST_TYPE" == "compliance" ] ; then pre-commit run --all-files ; fi
  - if [ "$TEST_TYPE" == "test" ] ; then cd tests; py.test ; fi
